ARG BUILDVERSION

# Build the manager binary
ARG BUILDPLATFORM

FROM --platform=$BUILDPLATFORM registry.access.redhat.com/ubi9/go-toolset:9.7-1774499506 AS bpfman-agent-build
ARG BUILDVERSION

# The following ARGs are set internally by docker/build-push-action in github actions
ARG TARGETOS
ARG TARGETARCH
ARG TARGETPLATFORM

ARG BUILDPLATFORM

RUN echo "TARGETOS=${TARGETOS}  TARGETARCH=${TARGETARCH}  BUILDPLATFORM=${BUILDPLATFORM}  TARGETPLATFORM=${TARGETPLATFORM}"

WORKDIR /usr/src/bpfman-operator

# Copy everything except what's excluded by the .dockerignore file.
COPY . .

# Build
# the GOARCH has not a default value to allow the binary be built according to the host where the command
# was called. For example, if we call make docker-build in a local env which has the Apple Silicon M1 SO
# the docker BUILDPLATFORM arg will be linux/arm64 when for Apple x86 it will be linux/amd64. Therefore,
# by leaving it empty we can ensure that the container and binary shipped on it will have the same platform.
ENV GOEXPERIMENT=strictfipsruntime
RUN VERSION_PKG="github.com/bpfman/bpfman-operator/internal/version" && \
    BUILD_VERSION="$(git describe --tags --dirty --always --long 2>/dev/null || echo 0.0.0-unknown)" && \
    BUILD_COMMIT="$(git rev-parse HEAD 2>/dev/null || echo unknown)" && \
    BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)" && \
    LDFLAGS="-X '${VERSION_PKG}.buildVersion=${BUILD_VERSION}' -X '${VERSION_PKG}.buildCommit=${BUILD_COMMIT}' -X '${VERSION_PKG}.buildDate=${BUILD_DATE}'" && \
    CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -tags strictfipsruntime -mod vendor -ldflags "${LDFLAGS}" -o bpfman-agent ./cmd/bpfman-agent/main.go && \
    CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -tags strictfipsruntime -mod vendor -ldflags "${LDFLAGS}" -o metrics-proxy ./cmd/metrics-proxy/main.go && \
    CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -tags strictfipsruntime -mod vendor -ldflags "${LDFLAGS}" -o bpfman-crictl ./cmd/bpfman-crictl/main.go


FROM --platform=$TARGETPLATFORM registry.access.redhat.com/ubi9/ubi-minimal:9.7-1773939694

ARG BUILDVERSION
ARG TARGETARCH
ARG TARGETPLATFORM

WORKDIR /
COPY --from=bpfman-agent-build /usr/src/bpfman-operator/bpfman-agent .
COPY --from=bpfman-agent-build /usr/src/bpfman-operator/metrics-proxy .
COPY --from=bpfman-agent-build /usr/src/bpfman-operator/bpfman-crictl .

COPY LICENSE /licenses/

LABEL name="bpfman/bpfman-agent" \
      com.redhat.component="bpfman-agent" \
      io.k8s.display-name="Bpfman Agent" \
      summary="Bpfman agent manages the eBPF programs lifecycle." \
      description="The bpfman-agent manage bpfman ebpf programs on every node." \
      io.k8s.description="The bpfman-agent manage bpfman programs on every node." \
      io.openshift.tags="bpfman-agent" \
      maintainer="support@redhat.com" \
      version=$BUILDVERSION \
      vendor="Red Hat, Inc."

ENTRYPOINT ["/bpfman-agent"]
