# The base image is expected to contain
# /bin/opm (with a serve subcommand) and /bin/grpc_health_probe
FROM brew.registry.redhat.io/rh-osbs/openshift-ose-operator-registry-rhel9:v4.20

# Copy files to final location and process in place
COPY catalog /configs/bpfman-operator
COPY hack/update_catalog.sh .

# USER root required because base image runs as uid=1001 but we need write access to /configs
USER root
RUN ./update_catalog.sh && rm ./update_catalog.sh

# Configure the entrypoint and command
ENTRYPOINT ["/bin/opm"]
CMD ["serve", "/configs", "--cache-dir=/tmp/cache"]

RUN /bin/opm serve /configs --cache-dir=/tmp/cache --cache-only

# Set DC-specific label for the location of the DC root directory
# in the image
LABEL operators.operatorframework.io.index.configs.v1=/configs
