# IntegrationTestScenario configuration for bpfman snapshot validation
#
# Apply to the cluster with:
#   oc apply -f .tekton/integration-test-scenarios.yaml
#
# This scenario validates that snapshots are self-consistent before
# allowing them to be released. This prevents releasing snapshots where
# the bundle's embedded image references don't match the actual component
# images in the snapshot.
---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: bpfman-ystream-snapshot-validation
  namespace: ocp-bpfman-tenant
spec:
  application: bpfman-ystream
  contexts:
    - name: application
      description: Validate snapshot consistency for all push events
  resolverRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/openshift/bpfman-operator
      - name: revision
        value: main
      - name: pathInRepo
        value: .tekton/snapshot-validation-pipeline.yaml
