# IntegrationTestScenario configuration for bpfman snapshot validation
#
# Apply to the cluster with:
#   oc apply -f .tekton/integration-test-scenarios.yaml
#
# This scenario validates that snapshots are self-consistent before
# allowing them to be released. Only runs when the bundle component
# updates, since the bundle is the release artifact.
---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: bpfman-ystream-snapshot-validation
  namespace: ocp-bpfman-tenant
spec:
  application: bpfman-ystream
  contexts:
    - name: component_bpfman-operator-bundle-ystream
      description: Validate snapshot only when bundle updates
  resolverRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/openshift/bpfman-operator
      - name: revision
        value: main
      - name: pathInRepo
        value: .tekton/snapshot-validation-pipeline.yaml
