apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/bpfman-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" &&
      (".tekton/ocp-bpfman-operator-catalog-ocp4-20-pull-request.yaml".pathChanged() ||
      ".tekton/ocp-bpfman-operator-catalog-ocp4-20-push.yaml".pathChanged() ||
      "Containerfile.catalog.openshift-4.20".pathChanged() ||
      "catalog/***".pathChanged() ||
      "rpms.in.yaml".pathChanged() ||
      "hack/update_catalog.sh".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fbc-4-20
    appstudio.openshift.io/component: ocp-bpfman-operator-catalog-ocp4-20
    pipelines.appstudio.openshift.io/type: build
  name: ocp-bpfman-operator-catalog-ocp4-20-on-push
  namespace: ocp-bpfman-tenant
spec:
  params:
  - name: build-source-image
    value: "true"
  - name: prefetch-input
    value: '{"packages": [{"type": "rpm"}]}'
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocp-bpfman-tenant/ocp-bpfman-operator-catalog-ocp4-20:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: Containerfile.catalog.openshift-4.20
  pipelineRef:
    name: build-fbc-pipeline
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}