apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: snapshot-validation
spec:
  description: |
    Validates snapshot consistency for bpfman releases by running
    hack/konflux/scripts/validate-snapshot.py from the repository.

    Checks that the bundle's embedded image references match the
    component images in the snapshot.
  params:
    - name: SNAPSHOT
      description: The JSON string of the Snapshot under test
      type: string
  tasks:
    - name: validate-snapshot
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
          - name: SNAPSHOT
            type: string
        results:
          - name: TEST_OUTPUT
            description: Test output in JSON format
        volumes:
          - name: source
            emptyDir: {}
        steps:
          - name: clone
            image: quay.io/konflux-ci/konflux-test:stable
            volumeMounts:
              - name: source
                mountPath: /source
            env:
              - name: SNAPSHOT
                value: $(params.SNAPSHOT)
            script: |
              #!/bin/bash
              set -euo pipefail

              # Extract git URL and revision from the bundle component
              # Use the bundle since it's what we're validating and has the latest revision
              REPO_URL=$(echo "$SNAPSHOT" | jq -r '.components[] | select(.name | contains("bundle")) | .source.git.url')
              REVISION=$(echo "$SNAPSHOT" | jq -r '.components[] | select(.name | contains("bundle")) | .source.git.revision')

              echo "=== Clone Info ==="
              echo "Repo: $REPO_URL"
              echo "Revision: $REVISION"
              echo ""

              if [ -z "$REPO_URL" ] || [ -z "$REVISION" ]; then
                echo "ERROR: Could not extract repo URL or revision from SNAPSHOT"
                echo "SNAPSHOT contents:"
                echo "$SNAPSHOT" | jq .
                exit 1
              fi

              git clone --depth 1 "$REPO_URL" /source/repo
              cd /source/repo
              git fetch origin "$REVISION" --depth 1
              git checkout "$REVISION"

              echo "Clone complete"

          - name: run-validation
            image: quay.io/konflux-ci/konflux-test:stable
            volumeMounts:
              - name: source
                mountPath: /source
            env:
              - name: SNAPSHOT
                value: $(params.SNAPSHOT)
            script: |
              #!/bin/bash
              set -euo pipefail

              SCRIPT="/source/repo/hack/konflux/scripts/validate-snapshot.py"

              if [ ! -f "$SCRIPT" ]; then
                echo "ERROR: Validation script not found at $SCRIPT"
                TIMESTAMP=$(date -u +%s)
                echo '{"result":"FAILURE","timestamp":"'"$TIMESTAMP"'","failures":1,"successes":0,"warnings":0}' | tee $(results.TEST_OUTPUT.path)
                exit 1
              fi

              echo "Running: $SCRIPT"
              echo ""

              # Run the validation script
              if python3 "$SCRIPT"; then
                RESULT="SUCCESS"
                FAILURES=0
                SUCCESSES=1
              else
                RESULT="FAILURE"
                FAILURES=1
                SUCCESSES=0
              fi

              echo ""
              TIMESTAMP=$(date -u +%s)
              echo '{"result":"'"$RESULT"'","timestamp":"'"$TIMESTAMP"'","failures":'"$FAILURES"',"successes":'"$SUCCESSES"',"warnings":0}' | tee $(results.TEST_OUTPUT.path)

              # Exit with appropriate code
              if [ "$RESULT" = "FAILURE" ]; then
                exit 1
              fi
